### ISSUE TITLE
suggestion: skip broken files

### ISSUE THREAD

**Issue by stunlocked1** [teticio/Deej-AI#49]
Often I get
```
Traceback (most recent call last):
  File "f:\Stuff\Programming\libs\deejAI.py", line 6, in <module>
    audio_encoder.encode(files)
  File "D:\Mambaforge\envs\audiodiffusion\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Mambaforge\envs\audiodiffusion\lib\site-packages\audiodiffusion\audio_encoder.py", line 89, in encode
    self.mel.load_audio(audio_file)
  File "D:\Mambaforge\envs\audiodiffusion\lib\site-packages\diffusers\pipelines\audio_diffusion\mel.py", line 98, in load_audio
    self.audio, _ = librosa.load(audio_file, mono=True, sr=self.sr)
  File "D:\Mambaforge\envs\audiodiffusion\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "D:\Mambaforge\envs\audiodiffusion\lib\site-packages\librosa\core\audio.py", line 218, in load
    y = resample(y, orig_sr=sr_native, target_sr=sr, res_type=res_type)
  File "D:\Mambaforge\envs\audiodiffusion\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "D:\Mambaforge\envs\audiodiffusion\lib\site-packages\librosa\core\audio.py", line 686, in resample
    y_hat = resampy.resample(y, orig_sr, target_sr, filter=res_type, axis=-1)
  File "D:\Mambaforge\envs\audiodiffusion\lib\site-packages\resampy\core.py", line 117, in resample
    raise ValueError(
ValueError: Input signal length=0 is too small to resample from 44100->22050
```
and it stops the whole program
example audiofile:
[100 gecs - Hand Crushed By A Mallet (Soup Remix).zip](https://github.com/teticio/Deej-AI/files/10721060/100.gecs.-.Hand.Crushed.By.A.Mallet.Soup.Remix.zip)

the issue is that when librosa opens it it has shape 2,0

if anyone has the same issue (i have it with every 20th mp3 approximately)
go to D:\Mambaforge\envs\audiodiffusion\lib\site-packages\diffusers\pipelines\audio_diffusion\mel.py
search for def load_audio
and replace 
if audio_file is not None:
    self.audio, _ = librosa.load(audio_file, mono=True, sr=self.sr)

with
if audio_file is not None:
            try:
                self.audio, _ = librosa.load(audio_file, mono=True, sr=self.sr)
            except:
                try:
                    import madmom
                    self.audio, _ = madmom.io.audio.load_audio_file(audio_file, dtype=float, sample_rate=self.sr, num_channels=1)
                    self.audio=self.audio.T
                except:
                    try:
                        import pedalboard.io
                        with pedalboard.io.AudioFile(audio_file).resampled_to(self.sr) as f:
                            self.audio = f.read(f.frames)
                            #samplerate = f.samplerate
                    except:
                        import soundfile
                        self.audio, _ = soundfile.read(audio_file, samplerate=self.sr, channels=1)
                        self.audio=self.audio.T

also install ffmpeg-python and pedalboard

**Comment by teticio** [comment]
I think this is a reasonable behaviour and the solution is to do something like you suggest, using `try` and `except`. Thanks!
